import type { ImageSourcePropType } from 'react-native';

// One local file per store logo (256 px, square). Metro needs each require written out in full.
export const BRAND_LOGOS: Record<string, ImageSourcePropType> = {
  'a-and-w': require('../assets/brands/a-and-w.png'),
  'adonis': require('../assets/brands/adonis.png'),
  'amazon': require('../assets/brands/amazon.png'),
  'anthropic': require('../assets/brands/anthropic.png'),
  'bell': require('../assets/brands/bell.png'),
  'best-buy': require('../assets/brands/best-buy.png'),
  'canadian-tire': require('../assets/brands/canadian-tire.png'),
  'chick-fil-a': require('../assets/brands/chick-fil-a.png'),
  'costco': require('../assets/brands/costco.png'),
  'dollarama': require('../assets/brands/dollarama.png'),
  'doordash': require('../assets/brands/doordash.png'),
  'enbridge': require('../assets/brands/enbridge.png'),
  'esso': require('../assets/brands/esso.png'),
  'farm-boy': require('../assets/brands/farm-boy.png'),
  'food-basics': require('../assets/brands/food-basics.png'),
  'freshco': require('../assets/brands/freshco.png'),
  'giant-tiger': require('../assets/brands/giant-tiger.png'),
  'h-and-m': require('../assets/brands/h-and-m.png'),
  'kfc': require('../assets/brands/kfc.png'),
  'loblaws': require('../assets/brands/loblaws.png'),
  'london-hydro': require('../assets/brands/london-hydro.png'),
  'mcdonalds': require('../assets/brands/mcdonalds.png'),
  'metro': require('../assets/brands/metro.png'),
  'mobil': require('../assets/brands/mobil.png'),
  'nike': require('../assets/brands/nike.png'),
  'no-frills': require('../assets/brands/no-frills.png'),
  'openai': require('../assets/brands/openai.png'),
  'pioneer': require('../assets/brands/pioneer.png'),
  'popeyes': require('../assets/brands/popeyes.png'),
  'real-canadian-superstore': require('../assets/brands/real-canadian-superstore.png'),
  'rogers': require('../assets/brands/rogers.png'),
  'shell': require('../assets/brands/shell.png'),
  'skip': require('../assets/brands/skip.png'),
  'starbucks': require('../assets/brands/starbucks.png'),
  'taco-bell': require('../assets/brands/taco-bell.png'),
  'td': require('../assets/brands/td.png'),
  'tim-hortons': require('../assets/brands/tim-hortons.png'),
  'uber': require('../assets/brands/uber.png'),
  'uber-eats': require('../assets/brands/uber-eats.png'),
  'walmart': require('../assets/brands/walmart.png'),
};
